// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/thumbnail.ts";
import * as $1 from "./routes/blog.tsx";
import * as $2 from "./routes/blog/[slug].tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/portfolio.tsx";

const manifest = {
  routes: {
    "./routes/api/thumbnail.ts": $0,
    "./routes/blog.tsx": $1,
    "./routes/blog/[slug].tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/portfolio.tsx": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
